name: codegen
channels:
  - conda-forge
  - defaults
  - huggingface
dependencies:
  - python==3.11
  - numpy==1.24.3
  - jax==0.4.23
  - jaxlib==0.4.23
  - flax==0.8.1
  - optax==0.1.9
  - datasets==2.18.0
  - transformers==4.38.2
  - scipy==1.11.3
  - typing-extensions>=4.5.0
